### ISSUE TITLE
删除文件后再新建文件会卡住；无法重命名文件

### ISSUE THREAD

**Issue by o-ut-man** [Blackman99/siyuan-plugin-vue-repl#1]
1.删除文件后，再点新建文件，就会卡住，只能重新刷新页面
![image](https://user-images.githubusercontent.com/34265164/233830152-5840a9b0-da81-43ee-b185-d8094d063ee0.png)
2.无法重命名文件，只能删除再新建

**Comment by Blackman99** [comment]
可以提供一下思源笔记以及挂件版本号吗
1. 我这里无法复现，很难定位问题
2. [官方 Vue REPL ](https://github.com/vuejs/repl) 没有此功能，但是有相关 Issue 以及 PR ，详见 https://github.com/vuejs/repl/pull/63

**Comment by o-ut-man** [comment]
> 可以提供一下思源笔记以及挂件版本号吗
> 
> 1. 我这里无法复现，很难定位问题
> 2. [官方 Vue REPL ](https://github.com/vuejs/repl) 没有此功能，但是有相关 Issue 以及 PR ，详见 [feat: add file renaming vuejs/repl#63](https://github.com/vuejs/repl/pull/63)

思源笔记 v2.8.5
挂件 v0.3.0

3. 怎么切换布局，刚用的时候还能左右，后来就变成按钮切换了
4. 打开文档时，切换到编辑的时候 ，不会显示代码， 要手动切换文件后才会显示

![111222224](https://user-images.githubusercontent.com/34265164/233830963-8549c177-afb4-4e42-bd94-d1f75aee6412.gif)

**Comment by Blackman99** [comment]
挂件容器宽度太小的情况下默认就会隐藏代码编辑，由浮动按钮切换，可以通过拖拽挂件宽度调整
你的设备信息可以提供一下吗

**Comment by Blackman99** [comment]
新版本中已经加入挂件宽度创建时自动置为容器宽度

**Comment by Blackman99** [comment]
0.8.0 版本支持文件重命名
