### ISSUE TITLE
建议：优化报错的提示方式

### ISSUE THREAD

**Issue by o-ut-man** [Blackman99/siyuan-plugin-vue-repl#3]
因为编辑器会自动检测错误，有时候代码敲一半的时候就会出现报错，而当前的报错方式会干扰到编辑区域，需要手动关闭提示

![image](https://user-images.githubusercontent.com/34265164/236626179-ee304df9-7b32-47e0-97ed-2ecae07d034b.png)

最好能优化一下，比如报错提示默认收缩，点击再展开

**Comment by Blackman99** [comment]
这个因为官方没有这个功能，不过可以通过其他方式实现，请耐心等待后续版本

**Comment by Blackman99** [comment]
PR：https://github.com/vuejs/repl/pull/98

**Comment by Blackman99** [comment]
自 0.9.0 版本起已增加该功能
