### ISSUE TITLE
挂件的宽度不会自适应

### ISSUE THREAD

**Issue by o-ut-man** [Blackman99/siyuan-plugin-vue-repl#4]
![1684312974625-20230517_163703](https://github.com/Blackman99/siyuan-plugin-vue-repl/assets/34265164/326a0080-aae3-450d-9e58-cf3dd5aa2552)

导致笔记宽度变更后，又需要去手动调整挂件宽度。最好能固定是【页面宽度】

**Comment by Blackman99** [comment]
包含此功能的 PR：#5

**Comment by Blackman99** [comment]
关闭此 issue，PR 已合并
