### ISSUE TITLE
loading之后就白屏

### ISSUE THREAD

**Issue by o-ut-man** [Blackman99/siyuan-plugin-vue-repl#6]
今天才出现这个问题，浏览器打开也一样
![image](https://github.com/Blackman99/siyuan-plugin-vue-repl/assets/34265164/38862349-80d1-459e-a86a-642b1499c7f8)

另外建议不论是用户端断网、服务端故障、网速慢等，先将代码内容显示出来，纯文本显示即可。

**Comment by Blackman99** [comment]
已在最新版 v0.6.0 中修复，请更新至新版本使用
并且将所有 js 下载至仓库内部，支持离线使用，加载速度巨幅提升，几乎不再能看到 Loading 字样

**Comment by Blackman99** [comment]
已解决，关闭此 issue
